number = int(input())

if number == 0:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

elif number == 1:
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()

elif number == 2:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")

elif number == 3:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")

elif number == 4:
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()

elif number == 5:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")

elif number == 6:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

elif number == 7:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()

elif number == 8:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

elif number == 9:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")